; =========================================================
; PLAYER PROFILE DATABASE
; Edit nilai di sini. Script membaca nama dropdown + statistik host.
; Score boleh positif, 0, atau negatif.
; =========================================================

[HOST1]
Name=PUTRY
Score=18
Wins=2
Deaths=20
EnemyKills=10

[HOST2]
Name=ASYA
Score=10
Wins=1
Deaths=1
EnemyKills=0

[HOST3]
Name=KIA
Score=37
Wins=4
Deaths=35
EnemyKills=83

[HOST4]
Name=KELA
Score=-3
Wins=0
Deaths=36
EnemyKills=7

